spring:
  application:
    name: twitter-srv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:twitterTest
    driver-class-name: org.h2.Driver
    password:
    username: sa
    initialization-mode: always



management:
  security:
    enabled: false
  server:
    port: 8082
  endpoints:
    web:
      base-path: ${server.servlet.context-path}/management
      exposure:
        include: '*'

server:
  port: 8081
  servlet:
    context-path: /twitter-srv

springfox:
  documentation:
    swagger:
      v2:
        path: ${server.servlet.context-path}/v2/api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

twitter:
  listenerEnabled: true
  tracks: COVID
  hashTagMoreUsed: 10
  followers: 1500
  languages: es,fr,it
  debug: true
  oauth:
    consumerKey: oq6hWq3qMkiz32uQI7d9d54qg
    consumerSecret: T0DqCPZ8T09uGHlwoa1lI15jTjrFeLRYWEpi2N95X7tkYMX3NA
    accessToken: 1380456707147632641-fLbqtYQObRYF8SFo8P49JQwX24Rs4U
    accessTokenSecret: acYG8iAakcIh7qo8EFtL3JLIUZXRNhZxcU4PuxxuiyYH8

---
spring:
  profiles: tests
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      write_dates_as_timestamps: false

twitter:
  listenerEnabled: false

